# Generated by Django 3.1.1 on 2020-09-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.TextField(max_length=120),
        ),
    ]
